#!/bin/bash

CONTAINERS=(
  adguardhome
  homeassistant
  wireguard
  wyze-bridge
)

install-container() {
  case $1 in
    adguardhome)
      if [[ ! -f /etc/resolv.conf.backup ]]; then
        sudo mkdir -p /etc/systemd/resolved.conf.d
        echo -e "[Resolve]\nDNS=127.0.0.1\nDNSStubListener=no" | sudo tee /etc/systemd/resolved.conf.d/adguardhome.conf > /dev/null

        sudo mv /etc/resolv.conf /etc/resolv.conf.backup
        sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf

        sudo systemctl reload-or-restart systemd-resolved
      fi

      mkdir -p ~/adguardhome/work
      mkdir -p ~/adguardhome/conf
      mkdir -p ~/certs

      docker pull adguard/adguardhome:latest
      docker stop adguardhome 2&>/dev/null
      docker rm adguardhome 2&>/dev/null

      docker run -d \
        --name adguardhome \
        --restart unless-stopped \
        -v /home/farmerbb/adguardhome/work:/opt/adguardhome/work \
        -v /home/farmerbb/adguardhome/conf:/opt/adguardhome/conf \
        -v /home/farmerbb/certs:/etc/letsencrypt \
        -p 53:53/tcp -p 53:53/udp \
        -p 80:80/tcp -p 443:443/tcp -p 443:443/udp -p 3000:3000/tcp \
        -p 853:853/tcp \
        adguard/adguardhome:latest || libvirt-dnsmasq-error
    ;;

    homeassistant)
      mkdir -p ~/Home\ Assistant
      mkdir -p ~/certs

      docker pull ghcr.io/home-assistant/home-assistant:stable
      docker stop homeassistant 2&>/dev/null
      docker rm homeassistant 2&>/dev/null

      docker run -d \
        --name homeassistant \
        --privileged \
        --restart=unless-stopped \
        -e TZ=America/Denver \
        -v /home/farmerbb/Home\ Assistant:/config \
        -v /home/farmerbb/certs:/etc/letsencrypt \
        --network=host \
        ghcr.io/home-assistant/home-assistant:stable
    ;;

    wireguard)
      docker pull lscr.io/linuxserver/wireguard:latest
      docker stop wireguard 2&>/dev/null
      docker rm wireguard 2&>/dev/null

      docker run -d \
        --name=wireguard \
        --cap-add=NET_ADMIN \
        -e PUID=1000 \
        -e PGID=1000 \
        -e TZ=America/Denver \
        -e SERVERURL=[REDACTED] \
        -e SERVERPORT=[REDACTED] \
        -e PEERS=5 \
        -e PEERDNS=none \
        -e ALLOWEDIPS=10.13.13.0/24,192.168.86.0/24,94.140.14.14/32 \
        -e LOG_CONFS=true \
        -p 51820:51820/udp \
        -v /mnt/files/Other\ Stuff/Linux/Network\ Config/WireGuard:/config \
        -v /mnt/files/Other\ Stuff/Linux/Network\ Config/ssh:/ssh \
        --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
        --restart unless-stopped \
        lscr.io/linuxserver/wireguard:latest

      docker exec -it wireguard /bin/bash -i -c \
        'apk add --update --no-cache openssh && cp -r /ssh /root/.ssh && chown -R root:root /root/.ssh && chmod 600 ~/.ssh/*'
    ;;

    wyze-bridge)
      docker pull mrlt8/wyze-bridge:latest
      docker stop wyze-bridge 2&>/dev/null
      docker rm wyze-bridge 2&>/dev/null

      docker run -d \
        --name=wyze-bridge \
        -e WYZE_EMAIL=[REDACTED] \
        -e WYZE_PASSWORD=$(echo [REDACTED] | base64 -d) \
        -e TOTP_KEY=[REDACTED] \
        -e ENABLE_AUDIO=true \
        -p 1935:1935 -p 8554:8554 -p 8888:8888 -p 5000:5000 \
        --restart unless-stopped \
        mrlt8/wyze-bridge:latest
    ;;
  esac
}

libvirt-dnsmasq-error() {
  echo
  echo "To fix dnsmasq conflicts with libvirt, run:"
  echo
  echo "    sudo virsh net-edit default"
  echo
  echo "and disable DNS with:"
  echo
  echo '    <dns enable="no" />'
  echo
}

print-usage() {
  BASENAME=$(basename "$0")
  echo -e "\033[1mContainers:\033[0m"
  for i in "${CONTAINERS[@]}"; do echo $i; done
  echo
  echo -e "\033[1mUsage:\033[0m $BASENAME  <install | start>  <container-name | all>"
  exit 1
}

[[ -z $(which docker) ]] && \
  echo "Please run install-docker before running this script." && \
  exit 1

[[ $# -ne 2 ]] && print-usage

if [[ "${CONTAINERS[@]}" =~ $2 || $2 = all ]]; then
  case $1 in
    start)
      if [[ $2 = all ]]; then
        for i in "${CONTAINERS[@]}"; do docker start $i; done
      else
        docker start $2
      fi
      exit 0
    ;;

    install)
      if [[ $2 = all ]]; then
        for i in "${CONTAINERS[@]}"; do install-container $i; done
      else
        install-container $2
      fi
      exit 0
    ;;

    *)
      print-usage
    ;;
  esac
fi

print-usage
