#!/bin/bash

NEW_CURSOR_SIZE=$1
[[ -z $NEW_CURSOR_SIZE ]] && NEW_CURSOR_SIZE=24

sleep 1
cd /tmp/.X11-unix

CURSOR_SIZE=$(echo "$(xdpyinfo | grep resolution | cut -d' ' -f 7 | cut -d'x' -f 1)/4" | bc | cut -d'.' -f 1)

for x in X*; do
  xsetroot -xcf /usr/share/icons/$XCURSOR_THEME/cursors/left_ptr $CURSOR_SIZE -d ":${x#X}"
  CURSOR_SIZE=$NEW_CURSOR_SIZE
done
