#!/bin/bash

PACKAGES=(
  86box:net._86box._86Box
  am2r:io.github.am2r_community_developers.AM2RLauncher
  cura:com.ultimaker.cura
  dolphin:org.DolphinEmu.dolphin-emu
  dosbox-x:com.dosbox_x.DOSBox-X
  eduke32:com.eduke32.EDuke32
  ezquake:io.github.ezQuake
  flatseal:com.github.tchx84.Flatseal
  gzdoom:org.zdoom.GZDoom
  heroic:com.heroicgameslauncher.hgl
  imhex:net.werwolv.ImHex
  jazz2:tk.deat.Jazz2Resurrection
  moonlight:com.moonlight_stream.Moonlight
  pegasus:org.pegasus_frontend.Pegasus
  pysol:io.sourceforge.pysolfc.PySolFC
  rigelengine:io.github.lethal_guitar.RigelEngine
  ryujinx:org.ryujinx.Ryujinx
  sonic3air:org.sonic3air.Sonic3AIR
  srb2:org.srb2.SRB2
  xemu:app.xemu.xemu
  yamagi:org.yamagi.YamagiQ2
)

install-package() {
  PACKAGE_ID=$(echo $1 | cut -d':' -f2)
  flatpak install --system -y flathub $PACKAGE_ID
  flatpak update --system -y $PACKAGE_ID
}

start-package() {
  PACKAGE_ID=$(echo $1 | cut -d':' -f2)
  flatpak run $PACKAGE_ID "${@:2}"
}

remove-package() {
  PACKAGE_ID=$(echo $1 | cut -d':' -f2)
  flatpak remove -y $PACKAGE_ID
}

print-usage() {
  BASENAME=$(basename "$0")
  echo -e "\033[1mPackages:\033[0m"
  for i in "${PACKAGES[@]}"; do echo $i | cut -d':' -f1; done
  echo
  echo -e "\033[1mUsage:\033[0m $BASENAME  <install | start | remove>  <package-name | all>"
  exit 1
}

[[ -z $(which flatpak) ]] && \
  echo "Please run install-flatpak before running this script." && \
  exit 1

[[ $# -lt 2 ]] && print-usage

if [[ "${PACKAGES[@]}" =~ "$2:" || $2 = all ]]; then
  case $1 in
    install)
      for i in "${PACKAGES[@]}"; do
        if [[ $2 = all ]]; then
          install-package $i
        elif [[ $i =~ "$2:" ]]; then
          install-package $i
        fi
      done
      exit 0
    ;;

    start)
      if [[ $2 = all ]]; then
        echo "Refusing to start all packages, aborting..."
        exit 1
      fi

      for i in "${PACKAGES[@]}"; do
        if [[ $i =~ "$2:" ]]; then
          start-package $i "${@:3}"
        fi
      done
      exit 0
    ;;

    remove)
      if [[ $2 = all ]]; then
        printf "Press Enter if you really want to remove all packages, or CTRL+C to abort..."
        read _
      fi

      for i in "${PACKAGES[@]}"; do
        if [[ $2 = all ]]; then
          remove-package $i
        elif [[ $i =~ "$2:" ]]; then
          remove-package $i
        fi
      done
      exit 0
    ;;

    *)
      print-usage
    ;;
  esac
fi

print-usage
