#!/bin/bash

if [[ $# -ne 1 ]]; then
  BASENAME=$(basename "$0")
  echo "Usage: $BASENAME <branch-name>"
  exit 1
fi

if [[ ! -d .git ]]; then
  BASENAME=$(basename "$0")
  echo "$BASENAME must be run at the root of your git repository."
  exit 1
fi

SCRATCH_DIR=../.scratch

rm -rf $SCRATCH_DIR
mkdir $SCRATCH_DIR

mv * $SCRATCH_DIR
mv .* $SCRATCH_DIR
mv $SCRATCH_DIR/.git .

git clean -xfd
git reset --hard
git checkout $1 2>/dev/null || git checkout -b $1

mv .git $SCRATCH_DIR
rm -rf *
rm -rf .*

mv $SCRATCH_DIR/* .
mv $SCRATCH_DIR/.* .
rm -rf $SCRATCH_DIR
