#!/bin/bash
if [[ $HOSTNAME != NUC ]]; then
    ssh nuc -o LogLevel=QUIET -t bash -i -c $(basename "$0")
    exit $?
fi

TOKEN=[REDACTED]
BACKUP_NAME="$(date +%Y%m%d-%H%M%S)"

curl -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -d '{}' https://[REDACTED]/api/services/backup/create

sudo chown -R $USER:$USER ~/Docker/homeassistant/backups/*.tar
for i in ~/Other\ Stuff/Docker ~/OneDrive/Other\ Stuff/Docker; do
  rm "$i"/homeassistant-*.tar
  cp ~/Docker/homeassistant/backups/*.tar "$i"/homeassistant-$BACKUP_NAME.tar
done

rm ~/Docker/homeassistant/backups/*.tar
