#!/bin/bash
if [[ $HOSTNAME != NUC ]]; then
    ssh nuc -o LogLevel=QUIET -t bash -i -c $(basename "$0")
    exit $?
fi

TOKEN=[REDACTED]
NEST_ID=[REDACTED]
BACKUP_NAME="$(date +%Y%m%d-%H%M%S)"

mkdir ~/temp-nest-media
sudo mv ~/Docker/homeassistant/nest/event_media/$NEST_ID/* ~/temp-nest-media

curl -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -d '{}' https://[REDACTED]/api/services/backup/create

sudo mv ~/temp-nest-media/* ~/Docker/homeassistant/nest/event_media/$NEST_ID
rm -r ~/temp-nest-media

sudo chown -R $USER:$USER ~/Docker/homeassistant/backups/*.tar
for i in ~/Other\ Stuff/Docker ~/OneDrive/Other\ Stuff/Docker; do
  rm "$i"/homeassistant-*.tar
  cp ~/Docker/homeassistant/backups/*.tar "$i"/homeassistant-$BACKUP_NAME.tar
done

rm ~/Docker/homeassistant/backups/*.tar
