#!/bin/bash

bashrc-additions() {
  source ~/Other\ Stuff/Linux/Bash\ Configs/bashrc-additions-$1.sh
}

IDE_DIRS=(
  "/opt/android-studio"
  "/home/$USER/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate*"
)

for i in ${IDE_DIRS[@]}; do
  [[ -d $i ]] && export IDE_DIR=$i && break
done

bashrc-additions linux-generic
[[ -d "$IDE_DIR" ]] && bashrc-additions android-dev
[[ -d ~/Docker ]] && bashrc-additions docker
[[ $(which gnome-shell) ]] && bashrc-additions gnome
[[ $(lsb_release -is 2>/dev/null) = Ubuntu ]] && bashrc-additions ubuntu

$(uname -r | grep "[m|M]icrosoft" > /dev/null) && IS_WSL=true
[[ ! -z $IS_WSL ]] && bashrc-additions wsl

case $(sudo dmidecode -s system-product-name 2>/dev/null) in
  "21RVCTO1WW")
    bashrc-additions thinkpad
  ;;

# "Kled")
#   bashrc-additions spin713
# ;;

  "NUC8i5BEK")
    bashrc-additions nuc
  ;;

# "B85M-D3V")
#   bashrc-additions pc
# ;;

  "Standard PC (Q35 + ICH9, 2009)")
    bashrc-additions vm
  ;;
esac

case $(tr -d '\0' 2>/dev/null < /proc/device-tree/model) in
  "Raspberry Pi 3 Model B Plus Rev 1.3")
    bashrc-additions pi
  ;;

  "Raspberry Pi 3 Model B Rev 1.2")
    bashrc-additions pi3
  ;;
esac

if [[ ! -z $IS_WSL ]]; then
  case $HOSTNAME in
    "spin713")
      bashrc-additions spin713
    ;;

    "PC")
      bashrc-additions pc
    ;;
  esac
fi

unset -f bashrc-additions
return 0 2>/dev/null

SOURCE_PATH=$(realpath "$0")
cat ~/.bashrc | grep -q "source \"$SOURCE_PATH\"" && \
  echo "Already installed, exiting..." && \
  exit 0

echo "Installing bash config..."
echo '' >> ~/.bashrc
echo "source \"$SOURCE_PATH\"" >> ~/.bashrc

$(uname -r | grep "[m|M]icrosoft" > /dev/null) || exit 0
[[ -f ~/.bash-preexec.sh ]] && exit 0

sudo apt-get update
sudo apt-get -y install curl
curl https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o ~/.bash-preexec.sh
