#!/bin/bash

sudo apt-get update
sudo apt-get install -y libfuse-dev build-essential git pkg-config

git clone https://github.com/spion/adbfs-rootless.git
cd adbfs-rootless
make
sudo mv adbfs /usr/local/bin
sudo chmod +x /usr/local/bin/adbfs
cd ..
rm -rf adbfs-rootless/
