#!/bin/bash

sudo apt-get -y install git
git clone https://github.com/StuartIanNaylor/zram-swap-config
cd zram-swap-config
chmod +x install.sh && sudo ./install.sh
cd ..
rm -rf zram-swap-config
sudo rm /usr/local/bin/zram-swap-config-uninstall.sh
