#!/bin/bash

sudo apt-get update
sudo apt-get -y install golang-go scdoc build-essential

rm -rf darkman
git clone https://gitlab.com/WhyNotHugo/darkman.git
cd darkman
git checkout 8bbd5a63

for i in $(cat Makefile | grep '${DESTDIR}${PREFIX}' | sed 's#^.*${DESTDIR}${PREFIX}#/usr#'); do
  sudo rm -f $i
done

make
sudo make install
cd ..
rm -rf darkman

mkdir -p ~/.local/share/dark-mode.d
echo "gsettings set org.gnome.desktop.interface gtk-theme 'Qogir-Dark'" > ~/.local/share/dark-mode.d/dark-theme.sh
echo "dconf write /org/gnome/shell/extensions/user-theme/name \"'Qogir-Dark'\"" >> ~/.local/share/dark-mode.d/dark-theme.sh
echo "ln -sfn ~/.themes/Qogir-Dark/gtk-4.0 ~/.config/gtk-4.0" >> ~/.local/share/dark-mode.d/dark-theme.sh
echo "sed -i 's/theme=Qogir-solid/theme=Qogir-dark-solid/g' ~/.config/Kvantum/kvantum.kvconfig" >> ~/.local/share/dark-mode.d/dark-theme.sh
chmod +x ~/.local/share/dark-mode.d/dark-theme.sh

mkdir -p ~/.local/share/light-mode.d
echo "gsettings set org.gnome.desktop.interface gtk-theme 'Qogir'" > ~/.local/share/light-mode.d/light-theme.sh
echo "dconf write /org/gnome/shell/extensions/user-theme/name \"'Qogir'\"" >> ~/.local/share/light-mode.d/light-theme.sh
echo "ln -sfn ~/.themes/Qogir/gtk-4.0 ~/.config/gtk-4.0" >> ~/.local/share/light-mode.d/light-theme.sh
echo "sed -i 's/theme=Qogir-dark-solid/theme=Qogir-solid/g' ~/.config/Kvantum/kvantum.kvconfig" >> ~/.local/share/light-mode.d/light-theme.sh
chmod +x ~/.local/share/light-mode.d/light-theme.sh

systemctl --user enable --now darkman.service

sudo rm -rf ~/go

echo
echo "Please go to Settings -> Privacy and make sure that Location Services are enabled, then reboot."
