#!/bin/bash

if [[ -z $(which wget) ]] ; then
  sudo apt-get update
  sudo apt-get install -y wget
fi

FONT_DIR=/usr/share/fonts/truetype/robotomono
if [[ ! -d $FONT_DIR ]]; then
  sudo wget --content-disposition -P $FONT_DIR \
  https://github.com/google/fonts/blob/10a708073179c32928eb894e53465fca8106772f/apache/robotomono/static/RobotoMono-{Bold,BoldItalic,Italic,Light,LightItalic,Medium,MediumItalic,Regular,Thin,ThinItalic}.ttf?raw=true
fi
