#!/bin/bash

sudo rm -rf bees
git clone https://github.com/Zygo/bees.git
cd bees

sudo apt-get -y install build-essential btrfs-progs markdown schedtool

make -j$(nproc)
sudo make install

cd ..
sudo rm -rf bees
