#!/bin/bash

echo "deb http://packages.azlux.fr/debian/ bullseye main" | sudo tee /etc/apt/sources.list.d/azlux.list
wget -qO - https://azlux.fr/repo.gpg.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install -y log2ram
sudo rm -f /usr/local/bin/uninstall-log2ram.sh
