#!/bin/bash

rm -rf kscript-*.zip kscript-*/

URL=$(curl -s https://api.github.com/repos/kscripting/kscript/releases/latest \
| grep "browser_download_url" \
| cut -d : -f 2,3 \
| tr -d \")

curl $URL -LOs
unzip -q kscript-*.zip

for i in kscript kscript.jar; do
  sudo cp kscript-*/bin/$i /usr/local/bin
done

sudo chmod -x /usr/local/bin/kscript.jar
rm -rf kscript-*.zip kscript-*/
