#!/bin/bash

sudo rm -rf bees
git clone https://github.com/Zygo/bees.git
cd bees

sudo apt-get -y install build-essential btrfs-progs markdown schedtool

make -j$(nproc)
sudo make install

cd ..
sudo rm -rf bees

echo "UUID=$(sudo btrfs filesystem show -m | grep uuid | cut -d' ' -f5)" | sudo tee /etc/bees/beesd.conf > /dev/null
echo 'DB_SIZE=$((128*1024*1024))' | sudo tee -a /etc/bees/beesd.conf > /dev/null
