#!/bin/bash

sudo apt-get update
sudo apt-get install -y wget build-essential

curl https://raw.githubusercontent.com/jarun/advcpmv/master/install.sh --create-dirs -o ./advcpmv/install.sh && (cd advcpmv && sh install.sh)

sudo mv ./advcpmv/advcp /usr/local/bin/advcp
sudo mv ./advcpmv/advmv /usr/local/bin/advmv

rm -rf advcpmv
