#!/bin/bash

RELEASE=$(lsb_release -cs)

sudo dpkg --add-architecture i386

sudo mkdir -pm755 /etc/apt/keyrings
sudo wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/$RELEASE/winehq-$RELEASE.sources

sudo apt-get update
sudo apt-get -y install --install-recommends winehq-devel
