#!/bin/bash

DARKMAN_PID=$(pidof darkman)
[[ ! -z $DARKMAN_PID ]] && sudo kill $DARKMAN_PID

sudo apt-get update
sudo apt-get -y install golang-go scdoc build-essential

rm -rf darkman
git clone https://gitlab.com/WhyNotHugo/darkman.git
cd darkman
# git checkout 8bbd5a63

for i in $(cat Makefile | grep '${DESTDIR}${PREFIX}' | sed 's#^.*${DESTDIR}${PREFIX}#/usr#'); do
  sudo rm -f $i
done

make
sudo make install PREFIX=/usr
cd ..
rm -rf darkman

mkdir -p ~/.local/share/dark-mode.d
echo '#!/bin/bash' > ~/.local/share/dark-mode.d/dark-theme.sh
echo "gsettings set org.gnome.desktop.interface gtk-theme 'Qogir-Dark'" >> ~/.local/share/dark-mode.d/dark-theme.sh
echo "dconf write /org/gnome/shell/extensions/user-theme/name \"'Qogir-Dark'\"" >> ~/.local/share/dark-mode.d/dark-theme.sh
echo "ln -sfn ~/.themes/Qogir-Dark/gtk-4.0 ~/.config/gtk-4.0" >> ~/.local/share/dark-mode.d/dark-theme.sh
echo "sed -i 's/theme=Qogir-solid/theme=Qogir-dark-solid/g' ~/.config/Kvantum/kvantum.kvconfig" >> ~/.local/share/dark-mode.d/dark-theme.sh
echo "sudo sed -i 's#/usr/bin/google-chrome-stable#/usr/bin/google-chrome-stable --flag-switches-begin --enable-features=WebContentsForceDark:inversion_method/cielab_based/image_behavior/none/foreground_lightness_threshold/150/background_lightness_threshold/205 --flag-switches-end#' /usr/share/applications/google-chrome.desktop" >> ~/.local/share/dark-mode.d/dark-theme.sh
chmod +x ~/.local/share/dark-mode.d/dark-theme.sh

mkdir -p ~/.local/share/light-mode.d
echo '#!/bin/bash' > ~/.local/share/light-mode.d/light-theme.sh
echo "gsettings set org.gnome.desktop.interface gtk-theme 'Qogir'" >> ~/.local/share/light-mode.d/light-theme.sh
echo "dconf write /org/gnome/shell/extensions/user-theme/name \"'Qogir'\"" >> ~/.local/share/light-mode.d/light-theme.sh
echo "ln -sfn ~/.themes/Qogir/gtk-4.0 ~/.config/gtk-4.0" >> ~/.local/share/light-mode.d/light-theme.sh
echo "sed -i 's/theme=Qogir-dark-solid/theme=Qogir-solid/g' ~/.config/Kvantum/kvantum.kvconfig" >> ~/.local/share/light-mode.d/light-theme.sh
echo "sudo sed -i 's#/usr/bin/google-chrome-stable --flag-switches-begin --enable-features=WebContentsForceDark:inversion_method/cielab_based/image_behavior/none/foreground_lightness_threshold/150/background_lightness_threshold/205 --flag-switches-end#/usr/bin/google-chrome-stable#' /usr/share/applications/google-chrome.desktop" >> ~/.local/share/light-mode.d/light-theme.sh
chmod +x ~/.local/share/light-mode.d/light-theme.sh

systemctl --user enable --now darkman.service

sudo rm -rf ~/go

echo
echo "Please go to Settings -> Privacy and make sure that Location Services are enabled, then reboot."
