#!/bin/bash

if [[ -z $(which wget) ]] ; then
  sudo apt-get update
  sudo apt-get install -y wget
fi

sudo rm -rf /usr/share/fonts/truetype/robotomono
sudo wget --content-disposition -P /usr/share/fonts/truetype/robotomono \
https://github.com/google/fonts/blob/10a708073179c32928eb894e53465fca8106772f/apache/robotomono/static/RobotoMono-{Bold,BoldItalic,Italic,Light,LightItalic,Medium,MediumItalic,Regular,Thin,ThinItalic}.ttf?raw=true
