#!/bin/bash

echo 'deb http://download.opensuse.org/repositories/filesystems:/snapper/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/filesystems:snapper.list
curl -fsSL https://download.opensuse.org/repositories/filesystems:snapper/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/filesystems_snapper.gpg > /dev/null
sudo apt-get update
sudo apt-get install -y snapper
sudo $(which snapper) -c home create-config /home/farmerbb
sudo chmod a+rx ~/.snapshots
sudo chown :farmerbb ~/.snapshots
