#!/bin/bash

wget -O- https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
echo "deb https://dl.bintray.com/celestia/releases-deb buster main" | sudo tee /etc/apt/sources.list.d/celestia-bintray.list > /dev/null
sudo apt-get update
sudo apt-get -y install celestia
