#!/bin/bash

DARKMAN_PID=$(pidof darkman)
[[ ! -z $DARKMAN_PID ]] && sudo kill $DARKMAN_PID

sudo apt-get update
sudo apt-get -y install golang-go scdoc build-essential

rm -rf darkman
git clone https://gitlab.com/WhyNotHugo/darkman.git
cd darkman
# git checkout 8bbd5a63

for i in $(cat Makefile | grep '${DESTDIR}${PREFIX}' | sed 's#^.*${DESTDIR}${PREFIX}#/usr#'); do
  sudo rm -f $i
done

make
sudo make install PREFIX=/usr
cd ..
rm -rf darkman

CHROME_DESKTOP=/usr/share/applications/google-chrome.desktop
bash -i -c "reset-config-file ${CHROME_DESKTOP}"

DARK_MODE_DIR=~/.local/share/dark-mode.d
mkdir -p $DARK_MODE_DIR
cp $CHROME_DESKTOP ${DARK_MODE_DIR}/google-chrome.desktop
sed -i 's#/usr/bin/google-chrome-stable#/usr/bin/google-chrome-stable --flag-switches-begin --enable-features=WebContentsForceDark:inversion_method/cielab_based/image_behavior/none/foreground_lightness_threshold/150/background_lightness_threshold/205 --flag-switches-end#' ${DARK_MODE_DIR}/google-chrome.desktop
sed -i 's/Name=Google Chrome/Name=Google Chrome (Dark)/' ${DARK_MODE_DIR}/google-chrome.desktop

echo '#!/bin/bash' > ${DARK_MODE_DIR}/dark-theme.sh
echo "gsettings set org.gnome.desktop.interface gtk-theme 'Qogir-Dark'" >> ${DARK_MODE_DIR}/dark-theme.sh
echo "dconf write /org/gnome/shell/extensions/user-theme/name \"'Qogir-Dark'\"" >> ${DARK_MODE_DIR}/dark-theme.sh
echo "ln -sfn ~/.themes/Qogir-Dark/gtk-4.0 ~/.config/gtk-4.0" >> ${DARK_MODE_DIR}/dark-theme.sh
echo "sed -i 's/theme=Qogir-solid/theme=Qogir-dark-solid/g' ~/.config/Kvantum/kvantum.kvconfig" >> ${DARK_MODE_DIR}/dark-theme.sh
echo "sudo cp ${DARK_MODE_DIR}/google-chrome.desktop ${CHROME_DESKTOP}" >> ${DARK_MODE_DIR}/dark-theme.sh
chmod +x ${DARK_MODE_DIR}/dark-theme.sh

LIGHT_MODE_DIR=~/.local/share/light-mode.d
mkdir -p $LIGHT_MODE_DIR
cp $CHROME_DESKTOP ${LIGHT_MODE_DIR}/google-chrome.desktop

echo '#!/bin/bash' > ${LIGHT_MODE_DIR}/light-theme.sh
echo "gsettings set org.gnome.desktop.interface gtk-theme 'Qogir'" >> ${LIGHT_MODE_DIR}/light-theme.sh
echo "dconf write /org/gnome/shell/extensions/user-theme/name \"'Qogir'\"" >> ${LIGHT_MODE_DIR}/light-theme.sh
echo "ln -sfn ~/.themes/Qogir/gtk-4.0 ~/.config/gtk-4.0" >> ${LIGHT_MODE_DIR}/light-theme.sh
echo "sed -i 's/theme=Qogir-dark-solid/theme=Qogir-solid/g' ~/.config/Kvantum/kvantum.kvconfig" >> ${LIGHT_MODE_DIR}/light-theme.sh
echo "sudo cp ${LIGHT_MODE_DIR}/google-chrome.desktop ${CHROME_DESKTOP}" >> ${LIGHT_MODE_DIR}/light-theme.sh
chmod +x ${LIGHT_MODE_DIR}/light-theme.sh

systemctl --user enable --now darkman.service

sudo rm -rf ~/go

echo
echo "Please go to Settings -> Privacy and make sure that Location Services are enabled, then reboot."
