#!/bin/bash

do-mount() {
  mountpoint -q ~/NUC || \
  sshfs nuc:/ ~/NUC -o follow_symlinks
}

do-unmount() {
# [[ "$PWD" == $(realpath ~/NUC) ]] && cd
  ssh -q -O stop nuc
  sudo umount ~/NUC 2> /dev/null || \
  sudo umount -f ~/NUC 2> /dev/null || \
  sudo umount -l ~/NUC 2> /dev/null
}

timeout 1 nc -z 192.168.86.10 22 2> /dev/null
if [[ $? = 0 ]]; then
  do-mount
  [[ $? != 0 ]] && do-unmount && do-mount
else
  do-unmount
fi
