#!/bin/bash

[[ -z $1 ]] && \
  echo "Usage: $(basename "$0") <path-to-chd>" && \
  exit 1

$(uname -r | grep "[m|M]icrosoft" > /dev/null) && IS_WSL=true
[[ $1 =~ \.chd$ ]] && IS_CHD=true

if [[ ! -z $IS_WSL ]]; then
  IMG_PATH="$(wslpath -w "$1")"
  if [[ $IS_CHD = true ]]; then
    /mnt/z/Games/Utilities/chdman/chdman.exe extractcd -i "$IMG_PATH" -o C:\\Users\\Braden\\AppData\\Local\\Temp\\temp.cue
    IMG_PATH=C:\\Users\\Braden\\AppData\\Local\\Temp\\temp.cue
  fi

  /mnt/z/Other\ Stuff/Utilities/ImgDrive/imgdrivecmd_x64.exe "$IMG_PATH"

  sleep 1
  /mnt/c/Windows/explorer.exe D:\\
else
# [[ -z $(which chdman) ]] && INSTALL_DEPENDENCIES=true
  [[ -z $(which fuseiso) ]] && INSTALL_DEPENDENCIES=true

  if [[ ! -z $INSTALL_DEPENDENCIES ]]; then
    sudo apt-get update
    sudo apt-get -y install fuseiso # mame-tools
  fi

  IMG_PATH="$(realpath "$1")"
  if [[ $IS_CHD = true ]]; then
    ~/Games/Utilities/chdman/chdman extractcd -i "$IMG_PATH" -o /tmp/temp.cue
    IMG_PATH=/tmp/temp.bin
  fi

  fuseiso -p "$IMG_PATH" /tmp/mnt

  open /tmp/mnt > /dev/null 2>&1
fi

echo
printf "Press Enter to unmount the disc image..."
read _

if [[ ! -z $IS_WSL ]]; then
  /mnt/z/Other\ Stuff/Utilities/ImgDrive/imgdrivecmd_x64.exe -u
  if [[ $IS_CHD = true ]]; then
    rm /mnt/c/Users/Braden/AppData/Local/Temp/temp.bin
    rm /mnt/c/Users/Braden/AppData/Local/Temp/temp.cue
  fi
else
  sudo umount /tmp/mnt
  if [[ $IS_CHD = true ]]; then
    rm /tmp/temp.bin
    rm /tmp/temp.cue
  fi
fi
