#!/bin/bash

list-filesystems() {
  if [[ ! -z "$1" ]]; then
    sudo modprobe nbd max_part=8
    sudo qemu-nbd --connect=/dev/nbd0 "$1" >/dev/null 2>&1
    sleep 1

    sudo fdisk /dev/nbd0 -l
    sudo qemu-nbd --disconnect /dev/nbd0 >/dev/null
    sudo rmmod nbd

    echo
  fi
}

print-usage() {
  list-filesystems "$1"

  BASENAME=$(basename "$0")
  echo "Usage: $BASENAME <img-name> <partition-name>"
  exit 1
}

if [[ $# -gt 1 ]]; then
  sudo modprobe nbd max_part=8
  sudo qemu-nbd --connect=/dev/nbd0 "$1" >/dev/null 2>&1
  sleep 1

  mkdir -p /tmp/mnt
  sudo mount -o ro "$2" /tmp/mnt
  open /tmp/mnt >/dev/null 2>&1

  printf "Press Enter to unmount the disk image..."
  read _

  sudo umount /tmp/mnt
  sudo qemu-nbd --disconnect /dev/nbd0 >/dev/null
  sudo rmmod nbd
  exit 0
fi

print-usage "$1"
