#!/bin/bash
MTP_DEVICE=/run/user/$UID/gvfs/*/
cd $MTP_DEVICE >/dev/null 2>&1 || \
  (echo "Please plug your phone in and enable MTP file transfer." && exit 1)

cd Internal\ shared\ storage/DCIM/Camera >/dev/null 2>&1 || \
  (echo "Unable to open the Camera directory on your phone." && exit 1)

echo "Starting (note that this may take a while to start)..."

for a in jpg mp4; do
  [[ $a == jpg ]] && BASEDIR=Unsorted\ Pictures
  [[ $a == mp4 ]] && BASEDIR=Unsorted\ Videos

  for b in 2022 2023 2024; do
    for c in 01 02 03 04 05 06 07 08 09 10 11 12; do
      mkdir -p "Media/$BASEDIR/$b/$c"
      mv -v PXL_$b$c*.$a "Media/$BASEDIR/$b/$c"
    done
  done
done

echo
echo "Now, move the Media directory into OneDrive, and:"
echo "  - Merge duplicate directories"
echo "  - Skip duplicate files"
echo
echo "Press Enter to open the file manager..."
read _

open .
