#!/bin/bash

start-bees() {
  [[ ! -z $(pidof bees) ]] && exit 1

  sudo umount /run/bees/mnt/* >/dev/null 2>&1
  sudo daemonize /usr/sbin/beesd $(sudo btrfs filesystem show -m | grep uuid | cut -d' ' -f5)
  while [[ -z $(pgrep bees) ]]; do sleep 1; done

  for i in $(pidof bees); do
    sudo schedtool -D -n20 $i
    sudo ionice -c3 -p $i
  done
}

CHARGING=$(cat /sys/class/power_supply/AC/online)
BATTERY=$(cat /sys/class/power_supply/BAT0/capacity)

if [[ $CHARGING = 1 && $BATTERY > 90 || $BATTERY = 100 ]]; then
  start-bees
else
  sudo pkill bees
fi
