#!/bin/bash
if [[ $# -eq 0 ]]; then
  BASENAME=$(basename "$0")
  echo "Usage: $BASENAME <shield | shield2> <additional-params>"
  exit 1
fi

case $1 in
  shield)
    DEVICE=$1
  # LOCAL_IP=$(ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')
  # [[ ! $LOCAL_IP =~ 192.168.86 ]] && DEVICE=$DEVICE-proxy

    adb connect $DEVICE
    sleep 1
  ;;

  shield2)
    DEVICE=0323118103330
  ;;
esac

if [[ ! -z $DISABLE_ANIMATIONS ]]; then
  adb -s $DEVICE shell settings put global window_animation_scale 0.0
  adb -s $DEVICE shell settings put global transition_animation_scale 0.0
  adb -s $DEVICE shell settings put global animator_duration_scale 0.0
fi

if [[ $DEVICE == *shield* ]]; then
  adb -s $DEVICE shell settings put global hdmi_one_touch_play_enabled 0
fi

scrcpy -s $DEVICE --audio-codec=aac "${@:2}"

if [[ ! -z $DISABLE_ANIMATIONS ]]; then
  adb -s $DEVICE shell settings put global window_animation_scale 1.0
  adb -s $DEVICE shell settings put global transition_animation_scale 1.0
  adb -s $DEVICE shell settings put global animator_duration_scale 1.0
fi

if [[ $DEVICE == *shield* ]]; then
  adb -s $DEVICE shell settings put global hdmi_one_touch_play_enabled 1
  adb -s $DEVICE shell input keyevent 26
fi
