#!/bin/bash
[[ ! $1 =~ .tar ]] && \
  echo "Usage: sync-arc-browser-images <path-to-tar-backup>" && \
  exit 1

DIRNAME=$(dirname $1)
[[ $DIRNAME = . ]] && DIRNAME=$(pwd)

WORKING_DIR=$1-working

cd "$DIRNAME"
rm -rf "$WORKING_DIR"

mkdir "$WORKING_DIR"
tar xf "$1" -C "$WORKING_DIR"

cd "$WORKING_DIR"

if [[ -d artwork ]]; then
  cd artwork
  mv box card
  mv boxback card-back
  cd ..

  IMG_DIR="net.floatingpoint.android.arcturus/files/game-images"
  DEST_DIR="OneDrive:Android/Backup/Emulation/$IMG_DIR"

  rclone sync -v artwork $DEST_DIR

  cd "$DIRNAME"
  tar -f "$1" --delete artwork
else
  cd "$DIRNAME"
fi

rm -rf "$WORKING_DIR"
