#!/bin/bash

print-usage() {
  BASENAME=$(basename "$0")
  echo "Usage: $BASENAME <name-of-vm> <optional-backup-name>"
  exit 1
}

[[ $# -ne 1 && $# -ne 2 ]] && print-usage

NAME=$2
[[ -z "$NAME" ]] && NAME="$(date +%Y%m%d)"

IMAGE_ORIGINAL=/mnt/VMs/$1.img
IMAGE_BACKUP=/mnt/VMs/backups/$1~$NAME.img
XML_BACKUP=/mnt/VMs/backups/$1~$NAME.xml

[[ ! -f "$IMAGE_ORIGINAL" ]] && print-usage

while sudo virsh list | grep $1 >/dev/null 2>&1; do
  echo "Not creating backup while VM is running"
  exit 1
done

[[ -f "$IMAGE_BACKUP" ]] && rm -f "$IMAGE_BACKUP"

# lsattr -l "$IMAGE_ORIGINAL" | grep -q No_COW
# if [[ $? = 0 ]]; then
#   touch "$IMAGE_BACKUP"
#   chattr +C "$IMAGE_BACKUP"
# fi

mkdir -p /mnt/VMs/backups
cp --reflink=auto --sparse=auto "$IMAGE_ORIGINAL" "$IMAGE_BACKUP"
sudo virsh dumpxml $1 > "$XML_BACKUP" 2>/dev/null || rm "$XML_BACKUP"

[[ $1 = macos* ]] && cp -r --reflink=auto --sparse=auto /mnt/VMs/OSX-KVM /mnt/VMs/backups/OSX-KVM~$NAME
