#!/bin/bash

if [[ -z $(which virt-sparsify) ]]; then
  sudo apt-get update
  sudo apt-get install -y guestfs-tools
fi

touch /tmp/.btrfs-maintenance
sudo pkill bees

for i in $(sudo ls -1 --ignore=OSX-KVM ~/VMs); do
  echo "Optimizing $i..."
  [[ -z $(pgrep -a qemu | grep $i) ]] && \
  sudo virt-sparsify --in-place ~/VMs/$i
  [[ ! -z $BTRFS_HOME_MNT ]] && sudo btrfs fi defrag -rf -czstd ~/VMs/$i
  echo
done

rm /tmp/.btrfs-maintenance
sudo rm -rf /var/tmp/.guestfs-0
