#!/bin/bash

touch /tmp/.btrfs-maintenance
sudo pkill bees

for i in $(sudo ls -1 --ignore=OSX-KVM ~/VMs); do
  echo "Optimizing $i..."
  [[ -z $(pgrep -a qemu | grep $i) ]] && \
  sudo virt-sparsify --in-place ~/VMs/$i
  sudo btrfs fi defrag -rf -czstd ~/VMs/$i
  echo
done

rm /tmp/.btrfs-maintenance
sudo rm -rf /var/tmp/.guestfs-0
