#!/bin/bash

[[ $1 != "win11-vfio" ]] && exit 0

case $2 in
  release)
    if [[ -f /tmp/vm-maintenance ]]; then
      timeout 1 sudo umount -a -t cifs -l
    elif [[ $(cat /proc/uptime | cut -d'.' -f1) < 30 ]]; then
      touch /tmp/vm-maintenance
    else
      sudo poweroff
    fi
  ;;
esac
