#!/bin/bash

[[ $1 != "win11-vfio" ]] && exit 0

case $2 in
  release)
    if [[ -f /tmp/vm-maintenance ]]; then
      timeout 1 sudo umount -a -t cifs -l
    else
      sudo poweroff
    fi
  ;;
esac
