#!/bin/bash

[[ $1 != "win11-vfio" ]] && exit 0

case $2 in
  release)
    timeout 10 sudo umount -a -t cifs -f
    if [[ -f /tmp/vm-maintenance ]]; then
      true
    elif [[ $(cat /proc/uptime | cut -d'.' -f1) -lt 30 ]]; then
      touch /tmp/vm-maintenance
    else
      sudo poweroff
    fi
  ;;
esac
